name: Linter Go # Nama dari GitHub Action ini

on: # Konfigurasi untuk trigger GitHub Action ketika ada push ke branch master
  push:
    branches:
      - master

jobs: # Konfigurasi untuk job yang akan dijalankan oleh GitHub Action
  lint:
    runs-on: ubuntu-latest # Konfigurasi untuk jenis OS yang digunakan

    steps: # Konfigurasi langkah-langkah yang akan dijalankan oleh job
      - name: Checkout code # Checkout kode dari repo
        uses: actions/checkout@v2

      - name: Set up Go # Konfigurasi Go yang digunakan
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.5' # Versi Go yang digunakan

      - name: Install Linter Module # Menginstal module linter
        run: go get golang.org/x/lint/golint

      - name: Install Linter # Menginstal linter
        run: go install golang.org/x/lint/golint

      - name: Run Linter # Menjalankan linter
        run: golint ./...

      - name: Upload Linter Results # Mengupload hasil linting
        uses: actions/upload-artifact@v2
        with:
          name: Lint Results # Nama hasil upload
          path: lint-results.txt # Path hasil linting yang diupload
