name: Test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Checkout kode dari repo
        uses: actions/checkout@v3

      - name: Set up Go # Konfigurasi Go yang digunakan
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.5' # Versi Go yang digunakan

      - name: Testing Go
        uses: n8maninger/action-golang-test@v1